### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by timon4ik2102** [timon4ik2102/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by romatotti2102** [comment]
I am a frontend developer. I am writing web pages in HTML,CSS, JS. I want to improve my skills and do it perfectly

**Comment by timon4ik2102** [comment]
Thank you
