### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by timon4ik2102** [timon4ik2102/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by romatotti2102** [comment]
https://www.facebook.com/profile.php?id=100001482226381
https://github.com/timon4ik2102
+380979872198
romatimchenko1984@gmail.com
