### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by timon4ik2102** [timon4ik2102/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by romatotti2102** [comment]
2001- student of Nizhyn Gogol State University
2007- 
graduate student of Institute of History of Ukraine of National Academy of Sciense
2011- 
received a Ph.D.
2011- reserch fellow of Institute of History of Ukraine of National Academy of Sciense
2018 - study HTML, CSS and JS
2019 - study at Rolling Scopes School, write my first web pages, make it responce and dynamic
2020 - 
received a certificate of RS Scholl
2020 - passed test at Binary Studio Academy
