### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by timon4ik2102** [timon4ik2102/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by romatotti2102** [comment]
_Dislikes:_  instagram, delusion, passive-aggressive bureaucracy, politics
_Likes:_ read books, history, footall, FC Roma, travel, improve skills
_Character:_ Resourceful entertainer, empathetic observer, meticulous fixer , spontaneous researcher, curious hedonist, 
_Wants:_ Become a professional developer, make an application in a team, learn Node.js
Languages: ukrainian, russian, english
_Skills:_ Create beautiful design of webpages, Managing independently simultaneous people and asset operations, Earning approval from the most meticulous and fastidious team members, work in team, good knowledge of HTML, CSS, JavaScript, BEM, SCSS, Webpack, ESlint, Experience with package managers(NPM), Experience with graphics editors
_Education and courses:_ 
Day to day - W3Schools, CSS Tricks, learn.javascript.ru, freeCodeCamp, MDN, Udemy, Codewars
-2019-2020 - HTML, CSS, JavaScript and Node.js courses at Rolling Scopes School
-2007-2010 - graduate student of Institute of History of Ukraine of National Academy of Sciense
- 2001-2007 student at  Mykola Gogol Nizhyn State University: graduated with honors
- 1990-2001 at Gymnasium 16 in Nizhyn with an emphasis on foreign languages study:  took 3rd place at the town Olympiad in history
